### ISSUE TITLE
Error when run command `celery -A QuizApp worker -l info` the above error occurred.

### ISSUE THREAD

**Issue by phanxuanphucnd** [Aron-S-G-H/django-chat-application#2]
```
~/phucpx/django-chat-application main ?1 > celery --app QuizApp worker -l info                                                                                                            py django 01:12:57
Usage: celery [OPTIONS] COMMAND [ARGS]...
Try 'celery --help' for help.

Error: Invalid value for '-A' / '--app': 
Unable to load celery application.
The module QuizApp was not found.
```

Hello
When i run command `celery -A QuizApp worker -l info` the above error occurred.

Can you show me how to fix it?

**Comment by phanxuanphucnd** [comment]
When sign in error:

![23131](https://github.com/Aron-S-G-H/django-chat-application/assets/32262730/5df8996a-3755-4f80-9633-a274671a58e5)

**Comment by Aron-S-G-H** [comment]
oh my bad , instead of QuizApp write ChatApp . correct command : celery -A ChatApp worker -l INFO . both errors will be fixed . Thank you for informing me .

**Comment by Aron-S-G-H** [comment]
And note that, for sending a one-time password via email, you should set your email and your email host password in 'EMAIL_HOST_USER' and 'EMAIL_HOST_PASSWORD' in 'settings.py'
